server:
  port: 8081
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQL9Dialect

  flyway:
    baseline-description: baseline
    baseline-version: 0.1.0
    baseline-on-migrate: true
    out-of-order: true
    user: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}