server:
  port: 8081
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  flyway:
    baseline-description: baseline
    baseline-version: 0.1.0
    baseline-on-migrate: true
    out-of-order: true
    user: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

github:
  client:
    clientId: ${GITHUB_CLIENT_ID}
    clientSecret: ${GITHUB_CLIENT_SECRET}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

google:
  client:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

gitlab:
  client:
    clientId: ${GITLAB_CLIENT_ID}
    clientSecret: ${GITLAB_CLIENT_SECRET}
    accessTokenUri: https://gitlab.com/oauth/token
    userAuthorizationUri:  https://gitlab.com/oauth/authorize
    clientAuthenticationScheme: form
    scope:
      - openid
      - api
  resource:
    userInfoUri: https://gitlab.com/api/v4/user

jetbrains:
  client:
    clientId: 0-0-0-0-0
    clientSecret: Q3B10rlpAEac
    accessTokenUri: http://localhost:8080/hub/api/rest/oauth2/token
    userAuthorizationUri: http://localhost:8080/hub/api/rest/oauth2/auth
    clientAuthenticationScheme: form
    grand_type: client_credentials
    scope:
    - 0-0-0-0-0
    state: some-unique-state-id
  resource:
    userInfoUri: http://localhost:8080/hub/api/users