server:
  port: 8081
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  jpa:
    show-sql: true
    database-platform: ${DATABASE_PLATFORM}
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: ${DATABASE_DIALECT}

  flyway:
    baseline-description: baseline
    baseline-version: 0.1.0
    baseline-on-migrate: true
    out-of-order: true
    user: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}