spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true