insert into achievement (id, type, level_number, "name")
values (1, 'level', 1, 'Newbie'),
       (2, 'level', 2, 'Beginner'),
       (3, 'level', 3, 'Green'),
       (4, 'level', 4, 'Newbie'),
       (5, 'level', 5, 'Rookie'),
       (6, 'level', 6, 'Novice'),
       (7, 'level', 7, 'Freshman'),
       (8, 'level', 8, 'Elementary'),
       (9, 'level', 9, 'Low-Junior'),
       (10, 'level', 10, 'Attaworker'),
--        (11, 'level', 11, 'Junior'),
--        (12, 'level', 12, 'Tuned in'),
--        (13, 'level', 13, 'Pre-Intermediate'),
--        (14, 'level', 14, 'Intermediate'),
--        (15, 'level', 15, 'Able'),
--        (16, 'level', 16, 'Average'),
--        (17, 'level', 17, 'Upper-Intermediate'),
--        (18, 'level', 18, 'Middle'),
--        (19, 'level', 19, 'Progressive'),
--        (20, 'level', 20, 'Competent'),
--        (21, 'level', 21, 'Confident'),
--        (22, 'level', 22, 'Skilled'),
--        (23, 'level', 23, 'Qualified'),
--        (24, 'level', 24, 'Pre-Advanced'),
--        (25, 'level', 25, 'Advanced'),
--        (26, 'level', 26, 'Efficient'),
--        (27, 'level', 27, 'Experienced'),
--        (28, 'level', 28, 'Senior'),
--        (29, 'level', 29, 'Sophisticated'),
--        (30, 'level', 30, 'Proficient'),
--        (31, 'level', 31, 'Expert'),
--        (32, 'level', 32, 'Master'),
--        (33, 'level', 33, 'Guru'),
--        (34, 'level', 34, 'Super user'),

       (35, 'extra', null, 'Time Expert'),
       (36, 'extra', null, 'Time Guru'),
       (37, 'extra', null, 'Symbol Expert'),
       (38, 'extra', null, 'Symbol Guru'),
       (39, 'extra', null, 'Newbie in failed commits'),
       (40, 'extra', null, 'Progressive in failed commits'),
       (41, 'extra', null, 'Failed commit Expert'),
       (42, 'extra', null, 'Newbie in commits'),
       (43, 'extra', null, 'Intermediate commiter'),
       (44, 'extra', null, 'Competent commiter'),
       (45, 'extra', null, 'Skilled commiter'),
       (46, 'extra', null, 'Advanced commiter'),
       (47, 'extra', null, 'Senior commiter'),
       (48, 'extra', null, 'Guru commiter'),
       (49, 'extra', null, 'Super commiter'),
       (50, 'extra', null, 'Hard-working worker'),
       (51, 'extra', null, 'Сonscientious worker'),
       (52, 'extra', null, 'Commited worker'),
       (53, 'extra', null, 'Persistent worker'),
       (54, 'extra', null, 'Bitter busy worker'),
       (55, 'extra', null, 'Crazy worker'),
       (56, 'extra', null, 'Alien-worker'),
       (57, 'extra', null, 'Skilled copy-paster'),
       (58, 'extra', null, 'Advanced copy-paster'),
       (59, 'extra', null, 'Senior copy-paster'),
       (60, 'extra', null, 'Guru copy-paster'),
       (61, 'extra', null, 'F user'),
       (62, 'extra', null, 'F lover'),
       (63, 'extra', null, 'F addicted'),
       (64, 'extra', null, 'F master'),
       (65, 'extra', null, 'Space fan'),
       (66, 'extra', null, 'Tab fun'),
       (67, 'extra', null, 'Newbie in failed executions'),
       (68, 'extra', null, 'Failed executions junior'),
       (69, 'extra', null, 'Failed executions middle'),
       (70, 'extra', null, 'Failed executions  master'),
       (71, 'extra', null, 'Failed executions  guru'),
       (72, 'extra', null, 'You`ve been coding for a year!'),
       (73, 'extra', null, '1 million symbols typed'),
       (74, 'extra', null, '500th successful commit'),
       (75, 'extra', null, '1,000th successful execution'),
       (76, 'extra', null, '500th failed commit'),
       (77, 'extra', null, '1,000th failed execution'),
       (78, 'extra', null, '1,000th Ctrl pressed'),

       (79, 'team', null, 'Junior contributor'),
       (80, 'team', null, 'Cool debugger'),
       (81, 'team', null, 'Middle contributor'),
       (82, 'team', null, 'Senior contributor'),
       (83, 'team', null, 'Guru contribitor'),
       (84, 'team', null, 'Experienced copypaster'),
       (85, 'team', null, 'Sofisticated copypaster'),
       (86, 'team', null, 'Super copypaster'),
       (87, 'team', null, 'Persistent contributor'),
       (88, 'team', null, 'Skilled team commiter'),
       (89, 'team', null, 'Efficient team commiter'),
       (90, 'team', null, 'Guru team commiter');
--        (91, 'team', null, 'Qualified'),
--        (92, 'team', null, 'Pre-Advanced'),
--        (93, 'team', null, 'Advanced'),
--        (94, 'team', null, 'Efficient'),
--        (95, 'team', null, 'Experienced'),
--        (96, 'team', null, 'Senior'),
--        (97, 'team', null, 'Sophisticated'),
--        (98, 'team', null, 'Proficient'),
--        (99, 'team', null, 'Expert'),
--        (100, 'team', null, 'Master'),
--        (101, 'team', null, 'Guru'),
--        (102, 'team', null, 'Super user');
