insert into achievement (id, type, level_number, "name")
values (1, 'level', 1, 'Newbie'),
       (2, 'level', 2, 'Beginner'),
       (3, 'level', 3, 'Green'),
       (4, 'level', 4, 'Newbie'),
       (5, 'level', 5, 'Rookie'),
       (6, 'level', 6, 'Novice'),
       (7, 'level', 7, 'Freshman'),
       (8, 'level', 8, 'Elementary'),
       (9, 'level', 9, 'Low-Junior'),
       (10, 'level', 10, 'Attaworker'),
       (11, 'level', 11, 'Junior'),
       (12, 'level', 12, 'Tuned in'),
       (13, 'level', 13, 'Pre-Intermediate'),
       (14, 'level', 14, 'Intermediate'),
       (15, 'level', 15, 'Able'),
       (16, 'level', 16, 'Average'),
       (17, 'level', 17, 'Upper-Intermediate'),
       (18, 'level', 18, 'Middle'),
       (19, 'level', 19, 'Progressive'),
       (20, 'level', 20, 'Competent'),
       (21, 'level', 21, 'Confident'),
       (22, 'level', 22, 'Skilled'),
       (23, 'level', 23, 'Qualified'),
       (24, 'level', 24, 'Pre-Advanced'),
       (25, 'level', 25, 'Advanced'),
       (26, 'level', 26, 'Efficient'),
       (27, 'level', 27, 'Experienced'),
       (28, 'level', 28, 'Senior'),
       (29, 'level', 29, 'Sophisticated'),
       (30, 'level', 30, 'Proficient'),
       (31, 'level', 31, 'Expert'),
       (32, 'level', 32, 'Master'),
       (33, 'level', 33, 'Guru'),
       (34, 'level', 34, 'Super user'),

       (35, 'extra', null, 'Newbie in failed commits'),
       (36, 'extra', null, 'Progressive in failed commits'),
       (37, 'extra', null, 'Failed commit Expert'),
       (38, 'extra', null, 'Newbie in commits'),
       (39, 'extra', null, 'Rookie'),
       (40, 'extra', null, 'Novice'),
       (41, 'extra', null, 'Freshman'),
       (42, 'extra', null, 'Elementary'),
       (43, 'extra', null, 'Low-Junior'),
       (44, 'extra', null, 'Attaworker'),
       (45, 'extra', null, 'Junior'),
       (46, 'extra', null, 'Tuned in'),
       (47, 'extra', null, 'Pre-Intermediate'),
       (48, 'extra', null, 'Intermediate'),
       (49, 'extra', null, 'Able'),
       (50, 'extra', null, 'Average'),
       (51, 'extra', null, 'Upper-Intermediate'),
       (52, 'extra', null, 'Middle'),
       (53, 'extra', null, 'Progressive'),
       (54, 'extra', null, 'Competent'),
       (55, 'extra', null, 'Confident'),
       (56, 'extra', null, 'Skilled'),
       (57, 'extra', null, 'Qualified'),
       (58, 'extra', null, 'Pre-Advanced'),
       (59, 'extra', null, 'Advanced'),
       (60, 'extra', null, 'Efficient'),
       (61, 'extra', null, 'Experienced'),
       (62, 'extra', null, 'Senior'),
       (63, 'extra', null, 'Sophisticated'),
       (64, 'extra', null, 'Proficient'),
       (65, 'extra', null, 'Time Expert'),
       (66, 'extra', null, 'Symbol Expert'),
       (67, 'extra', null, 'Time Guru'),
       (68, 'extra', null, 'Symbol Guru'),

       (69, 'team', null, 'Newbie'),
       (70, 'team', null, 'Beginner'),
       (71, 'team', null, 'Green'),
       (72, 'team', null, 'Newbie'),
       (73, 'team', null, 'Rookie'),
       (74, 'team', null, 'Novice'),
       (75 'team', null, 'Freshman'),
       (76, 'team', null, 'Elementary'),
       (77, 'team', null, 'Low-Junior'),
       (78, 'team', null, 'Attaworker'),
       (79, 'team', null, 'Junior'),
       (80, 'team', null, 'Tuned in'),
       (81, 'team', null, 'Pre-Intermediate'),
       (82, 'team', null, 'Intermediate'),
       (83, 'team', null, 'Able'),
       (84, 'team', null, 'Average'),
       (85, 'team', null, 'Upper-Intermediate'),
       (86, 'team', null, 'Middle'),
       (87, 'team', null, 'Progressive'),
       (88, 'team', null, 'Competent'),
       (89, 'team', null, 'Confident'),
       (90, 'team', null, 'Skilled'),
       (91, 'team', null, 'Qualified'),
       (92, 'team', null, 'Pre-Advanced'),
       (93, 'team', null, 'Advanced'),
       (94, 'team', null, 'Efficient'),
       (95, 'team', null, 'Experienced'),
       (96, 'team', null, 'Senior'),
       (97, 'team', null, 'Sophisticated'),
       (98, 'team', null, 'Proficient'),
       (99, 'team', null, 'Expert'),
       (100, 'team', null, 'Master'),
       (101, 'team', null, 'Guru'),
       (102, 'team', null, 'Super user');
